// Info Panels application code, for use with family trees as generated by the SVG Family-Tree Generator (SVG-FTG)
// Author:	A.C.Proctor	2-Jan-2021
//

var ip_none = "No notes available for ";

function ip_resetDivs (ev,type,inst,key) {
// Close any person or family notes panels that are currently open
    var prefix = type + inst + '_';
    var allElements = document.getElementsByTagName("div");
    for (var i = 0; i < allElements.length; i++) {
	if (allElements[i].id.indexOf(prefix) == 0) {
	    allElements[i].style.display='none';
	}
    }
    document.getSelection().removeAllRanges();
}

function ip_showDiv (ev,type,inst,key) {
// Open the corresponding notes panel for the specified person or family
    ip_resetDivs(ev,type,inst,key);
    var elem = nd_getNoteByKey(inst,key,type);
    if (elem === null) {
	if (ip_none.length > 0) {
	    mb_show ("Notes", ip_none + nd_description(inst,key,type),function(iBut){},
		{Icon: 'http://parallaxviewpoint.com/SVGcode/Information-Dialog.png'} );
        }
    } else {
        elem.style.display='';
        elem.scrollIntoView(false);
    }
}